# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import requests


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 621)
        MainWindow.setMinimumSize(QtCore.QSize(120, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_Superior = QtWidgets.QFrame(self.frame)
        self.frame_Superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_Superior.setStyleSheet("QFrame{\n"
"background-color:rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(61,61,61);\n"
"border-radius:20px;\n"
"}")
        self.frame_Superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Superior.setObjectName("frame_Superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_Superior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Menu = QtWidgets.QPushButton(self.frame_Superior)
        self.btn_Menu.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_Menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("barra-de-menus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Menu.setIcon(icon)
        self.btn_Menu.setIconSize(QtCore.QSize(38, 38))
        self.btn_Menu.setObjectName("btn_Menu")
        self.horizontalLayout.addWidget(self.btn_Menu)
        spacerItem = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_Superior)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("boton-menos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.btn_Cerrar = QtWidgets.QPushButton(self.frame_Superior)
        self.btn_Cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_Cerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("boton-cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Cerrar.setIcon(icon2)
        self.btn_Cerrar.setIconSize(QtCore.QSize(38, 38))
        self.btn_Cerrar.setObjectName("btn_Cerrar")
        self.horizontalLayout.addWidget(self.btn_Cerrar)
        self.verticalLayout_2.addWidget(self.frame_Superior)
        self.frame_Contenido = QtWidgets.QFrame(self.frame)
        self.frame_Contenido.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Contenido.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Contenido.setObjectName("frame_Contenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Contenido)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_Control = QtWidgets.QFrame(self.frame_Contenido)
        self.frame_Control.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_Control.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_Control.setStyleSheet("QFrame{\n"
"background-color:rgb(0,206,151);\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(61,61,61);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font:77 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-top-left-radius:20px;\n"
"border-botto,-left-radius:20px;\n"
"color:rgb(0,0,0);\n"
"font:77 10pt \"Arial Black\";\n"
"}")
        self.frame_Control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Control.setObjectName("frame_Control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_Control)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_Control)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_Control)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addWidget(self.frame_Control)
        self.frame_Pagina = QtWidgets.QFrame(self.frame_Contenido)
        self.frame_Pagina.setStyleSheet("QFrame{\n"
"background-color:rgb(61,61,61);\n"
"}\n"
"\n"
"QLabel{\n"
"font:87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(0,206,151);\n"
"border:0px solid #14C8DC;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"border:0px;\n"
"color:rgb(255,255,255);\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font:75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:rgb(61,61,61);\n"
"border-radius: 15px;\n"
"color:rgb(255,255,255);\n"
"font:77 10pt \"Arial Black\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(0,206,151);\n"
"border-radius: 15px;\n"
"color:rgb(0,0,0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"background-color: rgb(255,255,255);\n"
"color: rgb(0, 0, 0);\n"
"gridline-color: rgb(0,206,151);\n"
"font-size: 12pt;\n"
"color: #000000;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section{\n"
"background-color: rgb(0,206,151);\n"
"border: 1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"\n"
"\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}")
        self.frame_Pagina.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Pagina.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Pagina.setObjectName("frame_Pagina")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_Pagina)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_Pagina)
        self.stackedWidget.setMinimumSize(QtCore.QSize(120, 30))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Api = QtWidgets.QWidget()
        self.page_Api.setObjectName("page_Api")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_Api)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.page_Api)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.page_Api)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_Refrescar = QtWidgets.QPushButton(self.page_Api)
        self.btn_Refrescar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_Refrescar.setObjectName("btn_Refrescar")
        self.horizontalLayout_5.addWidget(self.btn_Refrescar)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page_Api)
        self.page_BD = QtWidgets.QWidget()
        self.page_BD.setObjectName("page_BD")
        self.stackedWidget.addWidget(self.page_BD)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_Pagina)
        self.verticalLayout_2.addWidget(self.frame_Contenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.horizontalLayout_4.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "API"))
        self.pushButton_2.setText(_translate("MainWindow", "BASE DATOS"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Column1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Column2"))
        self.btn_Refrescar.setText(_translate("MainWindow", "Refrescar"))

    def loaddata(self):
        url= 'https://62433a7fd126926d0c5d296b.mockapi.io/api/v1/usuarios'
        data=requests.get(url)

        if data.status_code==200:
                data = data.json()
                for e in data:
                        print(e['id'])
                        print(e['fec_alta'])
                        print(e['user_name'])
                        print(e['codigo_zip'])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
